# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaMenUsuario(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 190, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 190, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 190, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_extrato = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_extrato.setGeometry(QtCore.QRect(20, 230, 351, 321))
        self.textEdit_extrato.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit_extrato.setObjectName("textEdit_extrato")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 131, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Coronet_of_the_Imperial_Prince_of_Brazil.svg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Editar perfil"))
        self.pushButton_2.setText(_translate("MainWindow", "vendas"))
        self.pushButton_3.setText(_translate("MainWindow", "comprar"))
        self.pushButton_5.setText(_translate("MainWindow", "sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaMenUsuario()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
